### ISSUE TITLE
[Feature] - V10 & SWR

### ISSUE THREAD

**Issue by sannajammeh** [sannajammeh/trpc-swr#16]
With TRPC v10 being built having proxy based SWR hooks for it would be fantastic. Switching between SWR & React Query isn't so neat. 

I am willing to fork and start this work if you'd like any collaborators :)

**Comment by sachinraja** [comment]
I'm busy working on v10 core right now but I was going to get around to this before the major release. I'd be happy to review a PR for it though!

**Comment by sannajammeh** [comment]
@sachinraja I built a working prototype with only the useSWR hook in a local codebase. Before I start a PR I'd like to create an RFC for some features which will allow us to take full advantage of SWR (2.0 beta) and the vanilla tRPC proxies. Where would you like it to be placed?

**Comment by sachinraja** [comment]
A separate issue would be best for an RFC, thanks!

**Comment by sannajammeh** [comment]
Closing this as we have an RFC
