### ISSUE TITLE
Skip global instance of `createTRPCClient`

### ISSUE THREAD

**Issue by KATT** [sannajammeh/trpc-swr#2]
The readme currently tells you to create a global tRPC client instance.

This will be problematic when SSRing because the same TRPCClient will be used for all requests.

Instead, create the client in a `useState(() => ...` callback

Related:

- https://trpc.io/docs/react#3-add-trpc-providers
- https://discord.com/channels/867764511159091230/965891303621656576

**Comment by sachinraja** [comment]
I did see that in the docs but was unsure of the reason.

> This will be problematic when SSRing because the same TRPCClient will be used for all requests.

Could you elaborate on why this is problematic? Also note that this package doesn't do any special SSR logic like `@trpc/react` does. The only SSR you'll get with this package is through server side suspense.

**Comment by KATT** [comment]
Examples:

- A request from user A could be accidentally batched with user B
- Setting `headers:` on the instance will be global for _all_ requests in the app

**Comment by sachinraja** [comment]
Ah ok that makes sense. I'll fix the readme.
