### ISSUE TITLE
que: Can we use it in production?

### ISSUE THREAD

**Issue by ryadav96** [sannajammeh/trpc-swr#31]

**Comment by sannajammeh** [comment]
Unfortunately not with the newest release of tRPC. 

There’s a new RFC in #19 . Should be finished in the coming weeks

**Comment by alejandrobailo** [comment]
Hey team, any news about it? 
Thanks in advance.

**Comment by sannajammeh** [comment]
> Hey team, any news about it? 
> 
> Thanks in advance.

Hi,

We are waiting on transfer from Github to resolve deployments of the new Docs. Hopefully going through this week :)

**Comment by sannajammeh** [comment]
New docs are now deployed! We are in RC mode still.  All of our integration tests already pass. I'll be confident in releasing a production version once I've tested it in more real world scenarios. 

To try the RC, have a look at the docs:
https://trpc-swr.vercel.app/
