### ISSUE TITLE
useSWR opts type is incorrect

### ISSUE THREAD

**Issue by grefrit** [sannajammeh/trpc-swr#50]
<img width="594" alt="image" src="https://github.com/sannajammeh/trpc-swr/assets/45934058/07d3f7e5-89d2-4134-968d-9faf54f3524e">

it seems that useSWR hook is missing typing for SWR options. 

If you try to remove `{}` here, it works normally. https://github.com/sannajammeh/trpc-swr/blob/bb74ec59a881f97aeb9eca426f6f7d46c2e49875/packages/client/src/createSWRProxyHooks.tsx#L29

**Comment by sannajammeh** [comment]
Looking into this!

**Comment by sannajammeh** [comment]
Should be fixed now! Next v2.0.1 is building.
