### ISSUE TITLE
Export all types.

### ISSUE THREAD

**Issue by sannajammeh** [sannajammeh/trpc-swr#7]
Please ensure to export all types like TRPCContextState.

Its causing the library to not compile due to "Referecing type from external module, but cannot be named" error.

**Comment by sachinraja** [comment]
Thanks for reporting, fixed in https://github.com/sachinraja/trpc-swr/commit/b63c6cf27d18ee686fa4719ba68986c32d6c11ee
released in [`0.1.1`](https://github.com/sachinraja/trpc-swr/releases/tag/v0.1.1)
